---
apiVersion: v1
kind: Service
metadata:
  name: rustfs-service
  namespace: data
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9000'
spec:
  selector:
    app: rustfs
  type: NodePort
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      nodePort: 30900
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30901