apiVersion: v1
kind: Service
metadata:
  name: python-prometheus-demo
  namespace: prometheus-demo
  labels:
    app.kubernetes.io/name: python-prometheus-demo
    app.kubernetes.io/component: app
  annotations:
    # Mirrors pod annotations so service-level scraping also works
    # (used by ServiceMonitor-less setups that scrape Services directly)
    prometheus.io/scrape: "true"
    prometheus.io/port:   "8000"
    prometheus.io/path:   "/metrics"
    prometheus.io/scheme: "http"
spec:
  selector:
    app.kubernetes.io/name: python-prometheus-demo
  ports:
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: metrics
  type: ClusterIP
