apiVersion: v1
kind: Service
metadata:
  name: java-prometheus-demo
  namespace: prometheus-demo
  labels:
    app.kubernetes.io/name: java-prometheus-demo
    app.kubernetes.io/component: app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port:   "8000"
    prometheus.io/path:   "/metrics"
    prometheus.io/scheme: "http"
spec:
  selector:
    app.kubernetes.io/name: java-prometheus-demo
  ports:
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: metrics
  type: ClusterIP
